import os
from dotenv import load_dotenv
load_dotenv(override=True)

JWT_SECRET = os.getenv("JWT_SECRET")  
JWT_ALGORITHM = os.getenv("JWT_ALGORITHM")

ACCESS_TOKEN_EXPIRE_MINUTES= int(os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES", 30))
REFRESH_TOKEN_EXPIRE_DAYS = int(os.getenv("REFRESH_TOKEN_EXPIRE_DAYS", 7))

AUTH_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")
AUTH_ANDROID_CLIENT_ID = os.getenv("GOOGLE_ADNROID_CLIENT_ID")
AUTH_IOS_CLIENT_ID = os.getenv("GOOGLE_IOS_CLIENT_ID")


GOOGLE_CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET")

GOOGLE_CLOUD_API_KEY = os.getenv("GOOGLE_CLOUD_API_KEY")
GEMINI_API_KEY = os.getenv("GEMINI_APIKEY")

GOOGLE_CLOUD_PROJECT_ID = os.getenv("GOOGLE_CLOUD_PROJECT_ID")
MONGODB_URL = os.getenv("MONGODB_URL")


